name: Publish Package

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Configure npm authentication
        run: |
          # Create .npmrc file with auth token
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          # Set npm registry and auth token for Bun
          bunx npm config set registry https://registry.npmjs.org/
          bunx npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        env:
          NPM_TOKEN: \${{ secrets.NPM_TOKEN }}

      - name: Publish package
        run: bun publish --access public
        env:
          NPM_TOKEN: \${{ secrets.NPM_TOKEN }}
